version: '3.9'

services:
  backend:
    build:
      context: ./server
    container_name: mrehab-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./mrehab
    container_name: mrehab-frontend
    ports:
      - "3000:80"  # NGINX serves React on port 80 inside container
    env_file:
      - ./mrehab/.env
    restart: unless-stopped
    depends_on:
      - backend
